### ISSUE TITLE
curl-ca-bundle.crt isn't included in release

### ISSUE THREAD

**Issue by ZeroChaos-** [cloudshark/wireshark-plugin#5]
Is curl-ca-bundle.crt intentionally not shipped with 1.0.4?

**Comment by thomasp11** [comment]
This is intentional. The plugin will use the certificates from the underlying operating system by default. This option exists to use alternative CAs that don't have certificates supplied by the operating system or self-signed certificates if you are deploying your own CloudShark Enterprise instance and not using the one hosted at https://www.cloudshark.org.
